export const aiToolsList = [
  // --- CHATBOTS (50+) ---
  { name: "ChatGPT", category: "Chatbot", desc: "OpenAI's leading AI for text and reasoning.", link: "https://chat.openai.com", icon: "🤖" },
  { name: "Claude AI", category: "Chatbot", desc: "Smart, ethical assistant by Anthropic.", link: "https://claude.ai", icon: "🧠" },
  { name: "Google Gemini", category: "Chatbot", desc: "Multimodal AI integrated with Google services.", link: "https://gemini.google.com", icon: "💎" },
  { name: "Perplexity", category: "Search", desc: "AI search engine with real-time sources.", link: "https://perplexity.ai", icon: "🔍" },
  { name: "DeepSeek", category: "Chatbot", desc: "Powerful AI for coding and math logic.", link: "https://deepseek.com", icon: "🧬" },
  { name: "Grok", category: "Chatbot", desc: "Real-time AI by xAI (Elon Musk).", link: "https://x.ai", icon: "🐦" },
  { name: "Poe", category: "Chatbot", desc: "All-in-one platform for top AI models.", link: "https://poe.com", icon: "📲" },
  { name: "Character.ai", category: "Chatbot", desc: "Chat with customized AI personalities.", link: "https://character.ai", icon: "🎭" },
  { name: "Pi AI", category: "Chatbot", desc: "Friendly personal AI for conversation.", link: "https://pi.ai", icon: "🫂" },
  { name: "Mistral AI", category: "Chatbot", desc: "High-performance open-source AI models.", link: "https://mistral.ai", icon: "🌪️" },

  // --- IMAGE GENERATION (100+) ---
  { name: "Midjourney", category: "Image", desc: "Highest quality artistic AI images.", link: "https://midjourney.com", icon: "🎨" },
  { name: "DALL-E 3", category: "Image", desc: "OpenAI's precise text-to-image tool.", link: "https://openai.com/dall-e-3", icon: "🖼️" },
  { name: "Leonardo AI", category: "Image", desc: "Full feature AI image generation studio.", link: "https://leonardo.ai", icon: "🖌️" },
  { name: "Stable Diffusion", category: "Image", desc: "Powerful open-source image generation.", link: "https://stability.ai", icon: "🌈" },
  { name: "Adobe Firefly", category: "Image", desc: "Creative AI for design and Photoshop.", link: "https://adobe.com/firefly", icon: "✨" },
  { name: "Lexica Art", category: "Image", desc: "Search engine for Stable Diffusion art.", link: "https://lexica.art", icon: "📷" },
  { name: "Playground AI", category: "Image", desc: "Easy online image editor and generator.", link: "https://playground.com", icon: "🎠" },
  { name: "Canva AI", category: "Design", desc: "AI-powered design tools within Canva.", link: "https://canva.com", icon: "🖌️" },
  { name: "BlueWillow", category: "Image", desc: "Free-to-try high quality image generator.", link: "https://bluewillow.ai", icon: "🌳" },
  { name: "Ideogram", category: "Image", desc: "Best AI for text-heavy image designs.", link: "https://ideogram.ai", icon: "🅰️" },

  // --- VIDEO & ANIMATION (80+) ---
  { name: "Sora", category: "Video", desc: "Next-gen photorealistic text-to-video.", link: "https://openai.com/sora", icon: "🎥" },
  { name: "Runway Gen-3", category: "Video", desc: "Professional AI video editing suite.", link: "https://runwayml.com", icon: "🎬" },
  { name: "Luma Dream Machine", category: "Video", desc: "Instant high-quality video generation.", link: "https://lumalabs.ai", icon: "🌟" },
  { name: "Pika Art", category: "Video", desc: "AI for cinematic and animated videos.", link: "https://pika.art", icon: "👾" },
  { name: "HeyGen", category: "Video", desc: "AI avatars for professional marketing.", link: "https://heygen.com", icon: "👤" },
  { name: "Synthesia", category: "Video", desc: "Text-to-video with digital presenters.", link: "https://synthesia.io", icon: "📺" },
  { name: "InVideo AI", category: "Video", desc: "Generate complete videos for YouTube/Reels.", link: "https://invideo.io", icon: "📽️" },
  { name: "Kling AI", category: "Video", desc: "High-end cinematic video generation.", link: "https://klingai.com", icon: "🐲" },

  // --- CODING (70+) ---
  { name: "GitHub Copilot", category: "Coding", desc: "The standard AI for code completion.", link: "https://github.com/features/copilot", icon: "💻" },
  { name: "Cursor", category: "Coding", desc: "AI-first code editor built on VS Code.", link: "https://cursor.com", icon: "⚙️" },
  { name: "Replit Agent", category: "Coding", desc: "Build and deploy apps using prompts.", link: "https://replit.com", icon: "🏗️" },
  { name: "Bolt.new", category: "Coding", desc: "Full-stack web apps in the browser via AI.", link: "https://bolt.new", icon: "⚡" },
  { name: "Blackbox AI", category: "Coding", desc: "Fast code search and autocomplete.", link: "https://blackbox.ai", icon: "⬛" },
  { name: "V0.dev", category: "Coding", desc: "Vercel's AI for generating UI components.", link: "https://v0.dev", icon: "🔼" },
  { name: "Lovable", category: "Coding", desc: "Build full software with English prompts.", link: "https://lovable.dev", icon: "🚀" },
  { name: "Codeium", category: "Coding", desc: "Free, lightning-fast coding assistant.", link: "https://codeium.com", icon: "🗝️" },

  // --- WRITING & PRODUCTIVITY (100+) ---
  { name: "Jasper", category: "Writing", desc: "Enterprise AI for marketing content.", link: "https://jasper.ai", icon: "✍️" },
  { name: "Grammarly", category: "Writing", desc: "AI for error-free writing and tone.", link: "https://grammarly.com", icon: "✅" },
  { name: "Quillbot", category: "Writing", desc: "Advanced AI paraphrasing and summary.", link: "https://quillbot.com", icon: "✒️" },
  { name: "Writesonic", category: "Writing", desc: "SEO-optimized blog and article writer.", link: "https://writesonic.com", icon: "🚀" },
  { name: "Notion AI", category: "Productivity", desc: "Integrated AI in your workspace notes.", link: "https://notion.ai", icon: "📓" },
  { name: "Gamma", category: "Design", desc: "AI for slides, docs, and web pages.", link: "https://gamma.app", icon: "📊" },
  { name: "Otter.ai", category: "Audio", desc: "AI meeting notes and transcriptions.", link: "https://otter.ai", icon: "👂" },
  { name: "Fireflies.ai", category: "Productivity", desc: "Voice assistant for recording meetings.", link: "https://fireflies.ai", icon: "🐝" },

  // --- AUDIO & VOICE (100+) ---
  { name: "ElevenLabs", category: "Audio", desc: "Best AI voice cloning and TTS.", link: "https://elevenlabs.io", icon: "🎙️" },
  { name: "Suno AI", category: "Audio", desc: "Create complete songs with music & lyrics.", link: "https://suno.com", icon: "🎵" },
  { name: "Udio", category: "Audio", desc: "High-fidelity AI music creation studio.", link: "https://udio.com", icon: "🎼" },
  { name: "Murf AI", category: "Audio", desc: "Professional AI voiceovers for videos.", link: "https://murf.ai", icon: "🎤" },
  { name: "Audo Studio", category: "Audio", desc: "One-click noise removal for audio.", link: "https://audo.ai", icon: "🔇" },
  { name: "Speechify", category: "Audio", desc: "Turn any text into an AI audiobook.", link: "https://speechify.com", icon: "📚" }
// --- VIDEO & 3D (নতুন ২০টি) ---
  { name: "Kling AI", category: "Video", desc: "High-end cinematic AI video generator.", link: "https://klingai.com", icon: "🐲" },
  { name: "Viggle AI", category: "Video", desc: "Character motion and animation styling AI.", link: "https://viggle.ai", icon: "💃" },
  { name: "Hailuo AI", category: "Video", desc: "Creative video generation from MiniMax.", link: "https://hailuoai.com", icon: "🎈" },
  { name: "Wonder Dynamics", category: "Video", desc: "Automatically animate CG characters into scenes.", link: "https://wonderdynamics.com", icon: "🤖" },
  { name: "Spline AI", category: "Design", desc: "Generate 3D objects and scenes with prompts.", link: "https://spline.design", icon: "🧊" },
  { name: "Meshy AI", category: "Design", desc: "Fast 3D model generation for games.", link: "https://meshy.ai", icon: "🎮" },
  { name: "Kaiber", category: "Video", desc: "AI video generation for music artists.", link: "https://kaiber.ai", icon: "🎸" },
  { name: "DeepBrain AI", category: "Video", desc: "Create AI human videos for business.", link: "https://deepbrain.io", icon: "👔" },
  { name: "D-ID", category: "Video", desc: "Talking head avatars from images.", link: "https://d-id.com", icon: "🗣️" },
  { name: "Fliki", category: "Video", desc: "Turn blog posts into videos with AI voices.", link: "https://fliki.ai", icon: "📸" },
  { name: "Morph Studio", category: "Video", desc: "AI-powered filmmaking and clip generation.", link: "https://morphstudio.com", icon: "🎬" },
  { name: "PixVerse", category: "Video", desc: "Powerful multi-modal video creation.", link: "https://pixverse.ai", icon: "🌌" },
  { name: "Mochi 1", category: "Video", desc: "Open-source high fidelity video generation.", link: "https://genmo.ai", icon: "🍡" },
  { name: "Colossyan", category: "Video", desc: "AI video for workplace learning and training.", link: "https://colossyan.com", icon: "🏫" },
  { name: "InVideo AI", category: "Video", desc: "Turn any idea into video instantly.", link: "https://invideo.io", icon: "📹" },
  { name: "Synthesia", category: "Video", desc: "Professional AI video presentations.", link: "https://synthesia.io", icon: "🎤" },
  { name: "Deepshot", category: "Video", desc: "AI software for re-shooting video dialogue.", link: "https://deepshot.ai", icon: "🔫" },
  { name: "Elai.io", category: "Video", desc: "Generate AI videos from text for scale.", link: "https://elai.io", icon: "💻" },
  { name: "Sieve", category: "Video", desc: "Build complex video AI apps fast.", link: "https://sieve.id", icon: "🏗️" },
  { name: "Tavus", category: "Video", desc: "Personalized video messages at scale.", link: "https://tavus.io", icon: "💌" },

  // --- WRITING & MARKETING (নতুন ২০টি) ---
  { name: "Anyword", category: "Writing", desc: "AI copywriter with predictive performance.", link: "https://anyword.com", icon: "📈" },
  { name: "Copy.ai", category: "Writing", desc: "Automate marketing and sales copy.", link: "https://copy.ai", icon: "✍️" },
  { name: "Frase", category: "Writing", desc: "AI tool for SEO content research.", link: "https://frase.io", icon: "📈" },
  { name: "Surfer SEO", category: "Writing", desc: "AI-driven SEO content optimization.", link: "https://surferseo.com", icon: "🏄" },
  { name: "Rytr", category: "Writing", desc: "Budget-friendly AI writing assistant.", link: "https://rytr.me", icon: "🖊️" },
  { name: "Hoppy Copy", category: "Writing", desc: "AI for email marketing campaigns.", link: "https://hoppycopy.co", icon: "📧" },
  { name: "Wordtune", category: "Writing", desc: "Rewrite and refine your thoughts.", link: "https://wordtune.com", icon: "📝" },
  { name: "Sudowrite", category: "Writing", desc: "The AI companion for creative fiction writers.", link: "https://sudowrite.com", icon: "📖" },
  { name: "Lex", category: "Writing", desc: "A modern word processor with built-in AI.", link: "https://lex.page", icon: "🏢" },
  { name: "Writer", category: "Writing", desc: "Generative AI for the enterprise.", link: "https://writer.com", icon: "🏢" },
  { name: "Simplified", category: "Writing", desc: "One-stop shop for writing and design.", link: "https://simplified.com", icon: "🛠️" },
  { name: "Narrato", category: "Writing", desc: "AI content creation and workspace.", link: "https://narrato.io", icon: "📑" },
  { name: "LongShot AI", category: "Writing", desc: "Fact-checked long-form AI writing.", link: "https://longshot.ai", icon: "🎯" },
  { name: "ContentBot", category: "Writing", desc: "AI for advanced content automation.", link: "https://contentbot.ai", icon: "🤖" },
  { name: "Hypotenuse AI", category: "Writing", desc: "E-commerce focused product descriptions.", link: "https://hypotenuse.ai", icon: "📐" },
  { name: "Scalenut", category: "Writing", desc: "Managed SEO content workflow.", link: "https://scalenut.com", icon: "⚖️" },
  { name: "Peppertype", category: "Writing", desc: "Virtual content marketing assistant.", link: "https://peppercontent.io", icon: "🌶️" },
  { name: "Ink", category: "Writing", desc: "AI content shield and editor.", link: "https://inkforall.com", icon: "🖋️" },
  { name: "Outranking", category: "Writing", desc: "Data-driven SEO content strategy.", link: "https://outranking.io", icon: "🏁" },
  { name: "Bertha AI", category: "Writing", desc: "AI assistant for WordPress users.", link: "https://bertha.ai", icon: "👩" },

  // --- CODING & DATA (নতুন ২০টি) ---
  { name: "Phind", category: "Coding", desc: "Search engine for developers.", link: "https://phind.com", icon: "🔎" },
  { name: "Sourcegraph Cody", category: "Coding", desc: "AI that knows your entire codebase.", link: "https://sourcegraph.com/cody", icon: "🔍" },
  { name: "Tabnine", category: "Coding", desc: "Private AI code completion.", link: "https://tabnine.com", icon: "⌨️" },
  { name: "Amazon Q", category: "Coding", desc: "AWS-powered AI for developers.", link: "https://aws.amazon.com/q", icon: "☁️" },
  { name: "Codeium", category: "Coding", desc: "Fast and free AI code assistant.", link: "https://codeium.com", icon: "⚡" },
  { name: "MutableAI", category: "Coding", desc: "AI for software engineering documentation.", link: "https://mutable.ai", icon: "📘" },
  { name: "Debuild", category: "Coding", desc: "Low-code AI for building web apps.", link: "https://debuild.app", icon: "🏗️" },
  { name: "Enzyme", category: "Coding", desc: "No-code AI for smart contracts.", link: "https://enzyme.finance", icon: "🧪" },
  { name: "Biff", category: "Coding", desc: "AI-powered data visualization.", link: "https://biff.com", icon: "📊" },
  { name: "Akkio", category: "Coding", desc: "No-code AI for data prediction.", link: "https://akkio.com", icon: "🔮" },
  { name: "Julius AI", category: "Coding", desc: "Your personal AI data scientist.", link: "https://julius.ai", icon: "🧪" },
  { name: "MonkeyLearn", category: "Coding", desc: "No-code text analysis AI.", link: "https://monkeylearn.com", icon: "🐒" },
  { name: "Obviously AI", category: "Coding", desc: "Predictive analytics in minutes.", link: "https://obviously.ai", icon: "📉" },
  { name: "Polymer", category: "Coding", desc: "Turn spreadsheets into databases.", link: "https://polymersearch.com", icon: "🧬" },
  { name: "Bito", category: "Coding", desc: "Swiss army knife for developers.", link: "https://bito.ai", icon: "🍱" },
  { name: "AskCodi", category: "Coding", desc: "Your coding assistant for faster builds.", link: "https://askcodi.com", icon: "❓" },
  { name: "Warp AI", category: "Coding", desc: "Modern terminal with AI built-in.", link: "https://warp.dev", icon: "🖥️" },
  { name: "Supermaven", category: "Coding", desc: "Ultra-fast AI code completion.", link: "https://supermaven.com", icon: "🦸" },
  { name: "Stepsize AI", category: "Coding", desc: "AI for engineering reporting.", link: "https://stepsize.com", icon: "👟" },
  { name: "Pieces", category: "Coding", desc: "AI tool for managing code snippets.", link: "https://pieces.app", icon: "🧩" },

  // --- PRODUCTIVITY & AUDIO (নতুন ২০টি) ---
  { name: "Otter.ai", category: "Audio", desc: "Automated meeting notes and transcripts.", link: "https://otter.ai", icon: "👂" },
  { name: "Fireflies.ai", category: "Productivity", desc: "Record, transcribe and search meetings.", link: "https://fireflies.ai", icon: "🐝" },
  { name: "Descript", category: "Audio", desc: "Edit audio and video like a document.", link: "https://descript.com", icon: "🎙️" },
  { name: "Rewind AI", category: "Productivity", desc: "A search engine for your life.", link: "https://rewind.ai", icon: "⏮️" },
  { name: "Mem AI", category: "Productivity", desc: "The self-organizing workspace.", link: "https://mem.ai", icon: "🧠" },
  { name: "Taskade", category: "Productivity", desc: "AI agents for team workflows.", link: "https://taskade.com", icon: "✅" },
  { name: "Krisp", category: "Audio", desc: "Remove background noise from calls.", link: "https://krisp.ai", icon: "🔇" },
  { name: "SaneBox", category: "Productivity", desc: "AI for cleaning up your inbox.", link: "https://sanebox.com", icon: "📥" },
  { name: "Motion", category: "Productivity", desc: "AI calendar and task manager.", link: "https://usemotion.com", icon: "📅" },
  { name: "Superhuman", category: "Productivity", desc: "The fastest email experience with AI.", link: "https://superhuman.com", icon: "⚡" },
  { name: "Castmagic", category: "Audio", desc: "AI for podcast content automation.", link: "https://castmagic.io", icon: "🪄" },
  { name: "Mubert", category: "Audio", desc: "AI-generated royalty-free music.", link: "https://mubert.com", icon: "🎵" },
  { name: "Voicemaker", category: "Audio", desc: "Professional text to speech converter.", link: "https://voicemaker.in", icon: "🔈" },
  { name: "Riverside AI", category: "Audio", desc: "High-quality remote podcast recording.", link: "https://riverside.fm", icon: "🌊" },
  { name: "Cleanvoice AI", category: "Audio", desc: "Remove filler words from audio.", link: "https://cleanvoice.ai", icon: "🧹" },
  { name: "Podcastle", category: "Audio", desc: "Studio-quality recording and AI editing.", link: "https://podcastle.ai", icon: "🎙️" },
  { name: "Murf AI", category: "Audio", desc: "Versatile AI voice generator.", link: "https://murf.ai", icon: "🗣️" },
  { name: "Lovo AI", category: "Audio", desc: "Next-gen AI voice and cloning.", link: "https://lovo.ai", icon: "🔊" },
  { name: "Soundraw", category: "Audio", desc: "Custom music generation for creators.", link: "https://soundraw.io", icon: "🎶" },
  { name: "Boomy", category: "Audio", desc: "Create and publish AI songs instantly.", link: "https://boomy.com", icon: "💥" },

  // --- EDUCATION & MISC (নতুন ২০টি) ---
  { name: "WolframAlpha", category: "Education", desc: "Computational intelligence engine.", link: "https://wolframalpha.com", icon: "🔢" },
  { name: "Consensus", category: "Education", desc: "AI search engine for research papers.", link: "https://consensus.app", icon: "📑" },
  { name: "Elicit", category: "Education", desc: "AI research assistant for academics.", link: "https://elicit.org", icon: "🔬" },
  { name: "Quizgecko", category: "Education", desc: "AI quiz and test generator.", link: "https://quizgecko.com", icon: "📝" },
  { name: "Khanmigo", category: "Education", desc: "Khan Academy's AI tutor for students.", link: "https://khanacademy.org", icon: "🎓" },
  { name: "Humata AI", category: "Education", desc: "ChatGPT for your files and PDFs.", link: "https://humata.ai", icon: "📄" },
  { name: "ChatPDF", category: "Education", desc: "Chat with any PDF document.", link: "https://chatpdf.com", icon: "📁" },
  { name: "Scholarcy", category: "Education", desc: "AI summarizer for research articles.", link: "https://scholarcy.com", icon: "🏫" },
  { name: "Socratic", category: "Education", desc: "Google's AI app for homework help.", link: "https://socratic.org", icon: "🦉" },
  { name: "Brainly AI", category: "Education", desc: "AI-enhanced peer-to-peer learning.", link: "https://brainly.com", icon: "🧠" },
  { name: "Genei", category: "Education", desc: "AI for faster research and writing.", link: "https://genei.io", icon: "🧞" },
  { name: "Explainpaper", category: "Education", desc: "Simplifying academic papers with AI.", link: "https://explainpaper.com", icon: "📖" },
  { name: "The Rundown", category: "Education", desc: "AI news and learning platform.", link: "https://therundown.ai", icon: "📰" },
  { name: "Mindsmith", category: "Education", desc: "AI-powered course authoring.", link: "https://mindsmith.ai", icon: "💡" },
  { name: "Yippity", category: "Education", desc: "Convert text into quizzes instantly.", link: "https://yippity.io", icon: "✏️" },
  { name: "Futurepedia", category: "Education", desc: "Directory for AI tools and news.", link: "https://futurepedia.io", icon: "📚" },
  { name: "AI Lawyer", category: "Education", desc: "Personal AI legal assistant.", link: "https://ailawyer.pro", icon: "⚖️" },
  { name: "Looka", category: "Design", desc: "AI-powered brand and logo maker.", link: "https://looka.com", icon: "🎨" },
  { name: "Brandmark", category: "Design", desc: "Design a logo with AI in minutes.", link: "https://brandmark.io", icon: "🏢" },
  { name: "Khroma", category: "Design", desc: "The AI color tool for designers.", link: "https://khroma.co", icon: "🌈" },
// --- SEO & CONTENT OPTIMIZATION (২০টি) ---
  { name: "MarketMuse", category: "Writing", desc: "AI content planning and optimization software.", link: "https://marketmuse.com", icon: "📈" },
  { name: "Clearscope", category: "Writing", desc: "Top-tier SEO content optimization tool.", link: "https://clearscope.io", icon: "🎯" },
  { name: "Frase AI", category: "Writing", desc: "AI-powered tool for faster SEO research.", link: "https://frase.io", icon: "🔍" },
  { name: "WordLift", category: "Writing", desc: "AI that turns content into structured data.", link: "https://wordlift.io", icon: "🧠" },
  { name: "NeuralText", category: "Writing", desc: "All-in-one content marketing platform.", link: "https://neuraltext.com", icon: "🧬" },
  { name: "Dashword", category: "Writing", desc: "Simple SEO content optimization for writers.", link: "https://dashword.com", icon: "📊" },
  { name: "WriterZen", category: "Writing", desc: "Discovery and planning tool for SEO.", link: "https://writerzen.net", icon: "🧘" },
  { name: "Simplified AI", category: "Design", desc: "Design, write, and publish in one place.", link: "https://simplified.com", icon: "🛠️" },
  { name: "InLinks", category: "Writing", desc: "Entity-based SEO and internal linking tool.", link: "https://inlinks.com", icon: "🔗" },
  { name: "CanIRank", category: "Writing", desc: "AI that gives specific SEO instructions.", link: "https://canirank.com", icon: "🏆" },
  { name: "GrowthBar", category: "Writing", desc: "AI for blog posts and keyword research.", link: "https://growthbarhosting.com", icon: "🌱" },
  { name: "TextCortex", category: "Writing", desc: "Customizable AI assistant for high-level writing.", link: "https://textcortex.com", icon: "📜" },
  { name: "LongShot", category: "Writing", desc: "Fact-checked long-form AI writing assistant.", link: "https://longshot.ai", icon: "🎯" },
  { name: "Zutrix", category: "Writing", desc: "AI-powered rank tracker and SEO suite.", link: "https://zutrix.com", icon: "📉" },
  { name: "KWFinder", category: "Writing", desc: "AI tool for finding hidden long-tail keywords.", link: "https://mangools.com", icon: "🔑" },
  { name: "RankMath AI", category: "Writing", desc: "WordPress SEO plugin with built-in AI.", link: "https://rankmath.com", icon: "📈" },
  { name: "Seobility", category: "Writing", desc: "Comprehensive SEO audit and analysis tool.", link: "https://seobility.net", icon: "✅" },
  { name: "Sitechecker", category: "Writing", desc: "AI for monitoring website SEO health.", link: "https://sitechecker.pro", icon: "🩺" },
  { name: "Alli AI", category: "Writing", desc: "Automate SEO for any website instantly.", link: "https://alliai.com", icon: "🤖" },
  { name: "ContentatScale", category: "Writing", desc: "AI that writes human-like SEO blogs.", link: "https://contentatscale.ai", icon: "⚖️" },

  // --- BUSINESS & SALES AI (২০টি) ---
  { name: "Gong.io", category: "Business", desc: "AI that analyzes sales conversations.", link: "https://gong.io", icon: "📣" },
  { name: "Chorus.ai", category: "Business", desc: "Conversation intelligence for sales teams.", link: "https://chorus.ai", icon: "🎤" },
  { name: "Apollo.ai", category: "Business", desc: "AI-powered lead generation and sales.", link: "https://apollo.io", icon: "🚀" },
  { name: "Seamless.ai", category: "Business", desc: "Real-time search engine for B2B leads.", link: "https://seamless.ai", icon: "🔍" },
  { name: "Lavender", category: "Business", desc: "AI email assistant for sales professionals.", link: "https://lavender.ai", icon: "💜" },
  { name: "Regie.ai", category: "Business", desc: "AI for content and sales sequence generation.", link: "https://regie.ai", icon: "⚙️" },
  { name: "6sense", category: "Business", desc: "Predictive revenue AI for B2B marketing.", link: "https://6sense.com", icon: "👁️" },
  { name: "HubSpot AI", category: "Business", desc: "AI-powered CRM and marketing tools.", link: "https://hubspot.com", icon: "🧡" },
  { name: "ZoomInfo Chorus", category: "Business", desc: "AI for coaching and sales productivity.", link: "https://zoominfo.com", icon: "🏢" },
  { name: "Salesforce Einstein", category: "Business", desc: "Smart AI built into the world's #1 CRM.", link: "https://salesforce.com", icon: "☁️" },
  { name: "Clari", category: "Business", desc: "AI-driven revenue precision platform.", link: "https://clari.com", icon: "💎" },
  { name: "People.ai", category: "Business", desc: "Data-driven insights for sales and ops.", link: "https://people.ai", icon: "👥" },
  { name: "Drift", category: "Business", desc: "AI chatbots for conversational marketing.", link: "https://drift.com", icon: "💬" },
  { name: "Intercom Fin", category: "Business", desc: "Next-gen AI bot for customer support.", link: "https://intercom.com", icon: "📥" },
  { name: "Ada", category: "Business", desc: "AI for automated customer service at scale.", link: "https://ada.cx", icon: "🤖" },
  { name: "Zendesk Answer Bot", category: "Business", desc: "AI for instant customer help and support.", link: "https://zendesk.com", icon: "💁" },
  { name: "Freshworks Freddy", category: "Business", desc: "AI for customer and employee engagement.", link: "https://freshworks.com", icon: "🍓" },
  { name: "Tidio AI", category: "Business", desc: "AI customer support for small businesses.", link: "https://tidio.com", icon: "🗨️" },
  { name: "Cognism", category: "Business", desc: "AI-powered compliant B2B data.", link: "https://cognism.com", icon: "📉" },
  { name: "Crystal Knows", category: "Business", desc: "AI that predicts personality for sales.", link: "https://crystalknows.com", icon: "💎" },

  // --- CREATIVE TOOLS & LOGO (২০টি) ---
  { name: "Logomaster", category: "Design", desc: "AI-driven professional logo design.", link: "https://logomaster.ai", icon: "🏷️" },
  { name: "Tailor Brands", category: "Design", desc: "AI tool for branding and logo creation.", link: "https://tailorbrands.com", icon: "👔" },
  { name: "Namelix", category: "Business", desc: "AI-powered business name generator.", link: "https://namelix.com", icon: "🔡" },
  { name: "Looka AI", category: "Design", desc: "Design a brand you love with AI.", link: "https://looka.com", icon: "🎨" },
  { name: "Wix ADI", category: "Design", desc: "AI that builds a website for you.", link: "https://wix.com", icon: "🌐" },
  { name: "Durable", category: "Design", desc: "Build a website in 30 seconds with AI.", link: "https://durable.co", icon: "⏱️" },
  { name: "10Web", category: "Design", desc: "AI-powered WordPress platform.", link: "https://10web.io", icon: "🕸️" },
  { name: "Appy Pie AI", category: "Design", desc: "Build apps and websites without code.", link: "https://appypie.com", icon: "🥧" },
  { name: "VanceAI", category: "Image", desc: "AI photo enhancement and editing tools.", link: "https://vanceai.com", icon: "🖼️" },
  { name: "Let's Enhance", category: "Image", desc: "AI image upscaler and quality fixer.", link: "https://letsenhance.io", icon: "🔝" },
  { name: "WatermarkRemover", category: "Image", desc: "Remove watermarks using AI technology.", link: "https://watermarkremover.io", icon: "💧" },
  { name: "Profile Picture AI", category: "Image", desc: "Create perfect AI profile pictures.", link: "https://profilepicture.ai", icon: "🤳" },
  { name: "ClipDrop", category: "Image", desc: "AI tool to capture and edit visuals.", link: "https://clipdrop.co", icon: "✂️" },
  { name: "Cleanup.pictures", category: "Image", desc: "Remove any object from photos with AI.", link: "https://cleanup.pictures", icon: "🧹" },
  { name: "Deep Nostalgia", category: "Image", desc: "Animate old family photos with AI.", link: "https://myheritage.com", icon: "🕰️" },
  { name: "Rosebud AI", category: "Image", desc: "AI-generated stock photos and faces.", link: "https://rosebud.ai", icon: "🌹" },
  { name: "Generated Photos", category: "Image", desc: "Unique AI-generated faces for any use.", link: "https://generated.photos", icon: "👤" },
  { name: "Hotpot AI", category: "Design", desc: "Helpful AI tools for creating graphics.", link: "https://hotpot.ai", icon: "🍲" },
  { name: "Magic Eraser", category: "Image", desc: "AI tool for removing unwanted parts of images.", link: "https://magiceraser.io", icon: "🪄" },
  { name: "Remove.bg", category: "Image", desc: "Instant background removal with AI.", link: "https://remove.bg", icon: "✂️" },

  // --- HEALTH & PERSONAL AI (২০টি) ---
  { name: "Woebot Health", category: "Health", desc: "AI mental health ally for everyday help.", link: "https://woebothealth.com", icon: "🤖" },
  { name: "Wysa", category: "Health", desc: "AI chatbot for emotional support.", link: "https://wysa.io", icon: "🧘" },
  { name: "Ada Health", category: "Health", desc: "AI personalized health assessment.", link: "https://ada.com", icon: "🩺" },
  { name: "Babylon Health", category: "Health", desc: "AI-powered healthcare and diagnosis.", link: "https://babylonhealth.com", icon: "🏥" },
  { name: "Symptoma", category: "Health", desc: "AI search engine for medical symptoms.", link: "https://symptoma.com", icon: "🌡️" },
  { name: "Noom", category: "Health", desc: "AI-driven psychology for weight loss.", link: "https://noom.com", icon: "⚖️" },
  { name: "Sleep Cycle", category: "Health", desc: "AI sleep analysis and smart alarm.", link: "https://sleepcycle.com", icon: "😴" },
  { name: "Foodvisor", category: "Health", desc: "AI nutritionist that analyzes your plate.", link: "https://foodvisor.io", icon: "🥗" },
  { name: "Vi Health", category: "Health", desc: "AI personal trainer and fitness guide.", link: "https://vi.health", icon: "🏃" },
  { name: "Replika", category: "Health", desc: "The AI companion that cares about you.", link: "https://replika.ai", icon: "💬" },
  { name: "K Health", category: "Health", desc: "AI for personalized medical knowledge.", link: "https://khealth.com", icon: "🩺" },
  { name: "Youper", category: "Health", desc: "AI therapy for anxiety and depression.", link: "https://youper.ai", icon: "🧡" },
  { name: "Fitbod", category: "Health", desc: "AI that builds your workout plan.", link: "https://fitbod.me", icon: "🏋️" },
  { name: "Zocdoc AI", category: "Health", desc: "AI for finding and booking doctors.", link: "https://zocdoc.com", icon: "👨‍⚕️" },
  { name: "Ginger AI", category: "Health", desc: "On-demand mental healthcare with AI.", link: "https://ginger.com", icon: "💆" },
  { name: "BetterUp", category: "Health", desc: "AI-driven professional coaching.", link: "https://betterup.com", icon: "🚀" },
  { name: "Headspace AI", category: "Health", desc: "Personalized meditation and mindfulness.", link: "https://headspace.com", icon: "🧘" },
  { name: "Calm AI", category: "Health", desc: "AI-powered sleep and relaxation tools.", link: "https://calm.com", icon: "🌊" },
  { name: "Eight Sleep", category: "Health", desc: "AI-powered smart mattress and sleep tech.", link: "https://eightsleep.com", icon: "🛌" },
  { name: "Tonal", category: "Health", desc: "AI-powered home gym and personal trainer.", link: "https://tonal.com", icon: "🏋️‍♂️" },

  // --- MISC & TOOLS (২০টি) ---
  { name: "IfThisThenThat", category: "Productivity", desc: "AI automation for cross-platform tasks.", link: "https://ifttt.com", icon: "🔗" },
  { name: "Zapier", category: "Productivity", desc: "Automate your workflows with AI.", link: "https://zapier.com", icon: "⚡" },
  { name: "Bardeen AI", category: "Productivity", desc: "One-click automation for browser tasks.", link: "https://bardeen.ai", icon: "🪄" },
  { name: "Make.com", category: "Productivity", desc: "Visual automation for complex workflows.", link: "https://make.com", icon: "🏗️" },
  { name: "Levity AI", category: "Productivity", desc: "No-code AI for automating daily tasks.", link: "https://levity.ai", icon: "🎈" },
  { name: "Parabola", category: "Productivity", desc: "AI for automating data processes.", link: "https://parabola.io", icon: "📉" },
  { name: "Clay", category: "Business", desc: "AI-powered sales and networking tool.", link: "https://clay.com", icon: "🧱" },
  { name: "Axiom.ai", category: "Productivity", desc: "Browser automation without code.", link: "https://axiom.ai", icon: "🤖" },
  { name: "ClickUp AI", category: "Productivity", desc: "Integrated AI in project management.", link: "https://clickup.com", icon: "🖱️" },
  { name: "Monday.com AI", category: "Productivity", desc: "Smart project tracking and automation.", link: "https://monday.com", icon: "📅" },
  { name: "Asana Intelligence", category: "Productivity", desc: "AI for work management and clarity.", link: "https://asana.com", icon: "🏢" },
  { name: "Trello Butler", category: "Productivity", desc: "AI automation for your Trello boards.", link: "https://trello.com", icon: "📋" },
  { name: "Miro AI", category: "Productivity", desc: "AI assistance for visual collaboration.", link: "https://miro.com", icon: "🖌️" },
  { name: "Whimsical AI", category: "Productivity", desc: "AI for mind maps and flowcharts.", link: "https://whimsical.com", icon: "🧠" },
  { name: "Lucidspark AI", category: "Productivity", desc: "Smart whiteboard for team brainstorming.", link: "https://lucid.app", icon: "💡" },
  { name: "Craft AI", category: "Productivity", desc: "AI-powered document and note tool.", link: "https://craft.do", icon: "🛠️" },
  { name: "Slite AI", category: "Productivity", desc: "AI-powered knowledge base for teams.", link: "https://slite.com", icon: "📚" },
  { name: "Supernotes", category: "Productivity", desc: "AI for connected micro-note taking.", link: "https://supernotes.app", icon: "📝" },
  { name: "Tana AI", category: "Productivity", desc: "The AI-first node-based workspace.", link: "https://tana.inc", icon: "🌱" },
  { name: "Obsidian AI", category: "Productivity", desc: "Community AI plugins for your second brain.", link: "https://obsidian.md", icon: "💎" },
// --- TRAVEL & LIFESTYLE (নতুন ২০টি) ---
  { name: "Roam Around", category: "Travel", desc: "Build full travel itineraries in seconds.", link: "https://roamaround.io", icon: "✈️" },
  { name: "Vacay Chatbot", category: "Travel", desc: "Your personal AI travel advisor.", link: "https://usevacay.com", icon: "🏖️" },
  { name: "Tripnotes", category: "Travel", desc: "Intelligent maps and travel planning.", link: "https://tripnotes.ai", icon: "🗺️" },
  { name: "Mindtrip", category: "Travel", desc: "AI-powered discovery and booking platform.", link: "https://mindtrip.ai", icon: "🌍" },
  { name: "Skyscanner AI", category: "Travel", desc: "Find the best flight deals using AI.", link: "https://skyscanner.net", icon: "🎫" },
  { name: "ChefGPT", category: "Lifestyle", desc: "Get recipes based on what's in your fridge.", link: "https://chefgpt.xyz", icon: "👨‍🍳" },
  { name: "MealPractice", category: "Lifestyle", desc: "AI meal planning made simple.", link: "https://mealpractice.com", icon: "🍲" },
  { name: "FitGPT", category: "Lifestyle", desc: "AI-powered workout and fitness plans.", link: "https://fitgpt.ai", icon: "💪" },
  { name: "Hugging Face", category: "Developer", desc: "The GitHub for AI and Machine Learning models.", link: "https://huggingface.co", icon: "🤗" },
  { name: "Luma Labs", category: "Video", desc: "High-quality 3D video and scene captures.", link: "https://lumalabs.ai", icon: "📸" },
  { name: "Poly AI", category: "Business", desc: "Human-like customer service voice bots.", link: "https://poly.ai", icon: "📞" },
  { name: "FinChat", category: "Finance", desc: "ChatGPT for equity research and finance.", link: "https://finchat.io", icon: "📈" },
  { name: "StockGPT", category: "Finance", desc: "AI search for earnings call transcripts.", link: "https://stockgpt.com", icon: "💹" },
  { name: "Kadoa", category: "Tools", desc: "AI-powered web scraping and data extraction.", link: "https://kadoa.com", icon: "⛏️" },
  { name: "Browse AI", category: "Tools", desc: "Train a robot to scrape any website.", link: "https://browse.ai", icon: "🤖" },
  { name: "Bardeen", category: "Productivity", desc: "Browser automation for busy people.", link: "https://bardeen.ai", icon: "🪄" },
  { name: "Superus", category: "Research", desc: "Visualize complex info with AI mind maps.", link: "https://superusapp.com", icon: "🕸️" },
  { name: "Humata", category: "Research", desc: "Chat with long PDF technical documents.", link: "https://humata.ai", icon: "📑" },
  { name: "Wisdolia", category: "Education", desc: "Flashcard generator from any web article.", link: "https://wisdolia.com", icon: "🃏" },
  { name: "MagicSchool", category: "Education", desc: "AI tools for hardworking teachers.", link: "https://magicschool.ai", icon: "🏫" },

  // --- SOCIAL MEDIA & CONTENT (নতুন ২০টি) ---
  { name: "Predis.ai", category: "Marketing", desc: "Full social media post generator (Text+Video).", link: "https://predis.ai", icon: "📱" },
  { name: "Ocoya", category: "Marketing", desc: "Schedule and create social content with AI.", link: "https://ocoya.com", icon: "🗓️" },
  { name: "AdCreative.ai", category: "Marketing", desc: "Generate high-converting ad banners.", link: "https://adcreative.ai", icon: "💰" },
  { name: "InVideo AI", category: "Video", desc: "Generate faceless YouTube/TikTok videos.", link: "https://invideo.io", icon: "📽️" },
  { name: "Munch", category: "Video", desc: "Extract viral clips from long videos.", link: "https://getmunch.com", icon: "🍕" },
  { name: "OpusClip", category: "Video", desc: "One-click short-form video generator.", link: "https://opus.pro", icon: "🎬" },
  { name: "Vidyo.ai", category: "Video", desc: "Turn podcasts into social media shorts.", link: "https://vidyo.ai", icon: "📼" },
  { name: "Submagic", category: "Video", desc: "AI captions and emojis for videos.", link: "https://submagic.co", icon: "🖋️" },
  { name: "Captions.ai", category: "Video", desc: "The AI creative studio for talking videos.", link: "https://captions.ai", icon: "💬" },
  { name: "Thumbnail.ai", category: "Design", desc: "Create YouTube thumbnails with AI.", link: "https://thumbnail.ai", icon: "🖼️" },
  { name: "BlogToPod", category: "Audio", desc: "Convert blog posts into podcasts.", link: "https://blogtopod.com", icon: "🎙️" },
  { name: "Listnr", category: "Audio", desc: "AI voiceovers for content creators.", link: "https://listnr.ai", icon: "🔊" },
  { name: "Podcastle", category: "Audio", desc: "Pro studio in your browser with AI.", link: "https://podcastle.ai", icon: "🎧" },
  { name: "Audials", category: "Audio", desc: "AI-enhanced audio and music recording.", link: "https://audials.com", icon: "📻" },
  { name: "Beatoven.ai", category: "Audio", desc: "Royalty-free AI background music.", link: "https://beatoven.ai", icon: "🎵" },
  { name: "Soundraw", category: "Audio", desc: "Unlimited music for your content.", link: "https://soundraw.io", icon: "🎹" },
  { name: "Riverside", category: "Video", desc: "High-quality remote video recording.", link: "https://riverside.fm", icon: "🌊" },
  { name: "Descript", category: "Video", desc: "Edit video by editing text.", link: "https://descript.com", icon: "📝" },
  { name: "Kits AI", category: "Audio", desc: "AI voice platform for musicians.", link: "https://kits.ai", icon: "🎤" },
  { name: "Voicify", category: "Audio", desc: "Create AI music covers in seconds.", link: "https://voicify.ai", icon: "🎭" },

  // --- GAMING & 3D (নতুন ২০টি) ---
  { name: "Scenario", category: "Gaming", desc: "AI-generated game assets and environments.", link: "https://scenario.com", icon: "🎮" },
  { name: "Leonardo.ai", category: "Image", desc: "High-quality AI art for game devs.", link: "https://leonardo.ai", icon: "🎨" },
  { name: "Blockade Labs", category: "Design", desc: "Create 360-degree worlds from text.", link: "https://blockadelabs.com", icon: "🌐" },
  { name: "Rosebud AI", category: "Gaming", desc: "AI-powered character and world creation.", link: "https://rosebud.ai", icon: "🌹" },
  { name: "Latent Labs", category: "Design", desc: "Text-to-360 panoramic world gen.", link: "https://latentlabs.art", icon: "🌌" },
  { name: "Skybox AI", category: "Gaming", desc: "Generate instant 3D game skyboxes.", link: "https://skybox.blockadelabs.com", icon: "☁️" },
  { name: "Promethean AI", category: "Gaming", desc: "AI for building virtual game worlds.", link: "https://prometheanai.com", icon: "🏗️" },
  { name: "Inworld AI", category: "Gaming", desc: "AI NPCs with realistic personalities.", link: "https://inworld.ai", icon: "👥" },
  { name: "Convai", category: "Gaming", desc: "Conversational AI for virtual characters.", link: "https://convai.com", icon: "🗣️" },
  { name: "Sloyd AI", category: "Design", desc: "Generate 3D models instantly.", link: "https://sloyd.ai", icon: "🧊" },
  { name: "Polyhive", category: "Gaming", desc: "AI texturing for 3D assets.", link: "https://polyhive.ai", icon: "🐝" },
  { name: "Kaedim", category: "Design", desc: "Turn 2D images into 3D models.", link: "https://kaedim3d.com", icon: "📦" },
  { name: "Veed.io", category: "Video", desc: "Complete AI video editing suite.", link: "https://veed.io", icon: "✂️" },
  { name: "Pictory", category: "Video", desc: "Turn articles into short social videos.", link: "https://pictory.ai", icon: "🎞️" },
  { name: "D-ID", category: "Video", desc: "AI talking avatars from photos.", link: "https://d-id.com", icon: "👤" },
  { name: "Synthesia", category: "Video", desc: "Professional AI video presenters.", link: "https://synthesia.io", icon: "📺" },
  { name: "HeyGen", category: "Video", desc: "AI video generation for teams.", link: "https://heygen.com", icon: "👔" },
  { name: "Colossyan", category: "Video", desc: "AI videos for workplace learning.", link: "https://colossyan.com", icon: "🎓" },
  { name: "DeepBrain", category: "Video", desc: "Realistic AI human video generators.", link: "https://deepbrain.io", icon: "🧠" },
  { name: "Elai", category: "Video", desc: "Build AI videos from text prompts.", link: "https://elai.io", icon: "💻" },

  // --- WEB3, DATA & SECURITY (নতুন ২০টি) ---
  { name: "ChainGPT", category: "Web3", desc: "AI for blockchain and crypto analysis.", link: "https://chaingpt.org", icon: "⛓️" },
  { name: "Bitsniper", category: "Web3", desc: "AI-powered crypto trading assistant.", link: "https://bitsniper.io", icon: "🎯" },
  { name: "Dune AI", category: "Data", desc: "Natural language for crypto data query.", link: "https://dune.com", icon: "📊" },
  { name: "Nanonets", category: "Data", desc: "AI-powered OCR and data capture.", link: "https://nanonets.com", icon: "📂" },
  { name: "Rossum", category: "Business", desc: "AI for automated document processing.", link: "https://rossum.ai", icon: "📄" },
  { name: "Abnormal Security", category: "Security", desc: "AI-powered email security platform.", link: "https://abnormalsecurity.com", icon: "🛡️" },
  { name: "Darktrace", category: "Security", desc: "Self-learning AI for cybersecurity.", link: "https://darktrace.com", icon: "🕵️" },
  { name: "Snyk AI", category: "Security", desc: "Find and fix code vulnerabilities.", link: "https://snyk.io", icon: "🔒" },
  { name: "Vanta", category: "Security", desc: "AI for automated compliance and trust.", link: "https://vanta.com", icon: "📜" },
  { name: "BigID", category: "Security", desc: "AI for data privacy and protection.", link: "https://bigid.com", icon: "💾" },
  { name: "Tessian", category: "Security", desc: "AI-powered cloud email security.", link: "https://tessian.com", icon: "📩" },
  { name: "SentinelOne", category: "Security", desc: "AI endpoint protection platform.", link: "https://sentinelone.com", icon: "💂" },
  { name: "CrowdStrike", category: "Security", desc: "AI-driven threat intelligence.", link: "https://crowdstrike.com", icon: "🦅" },
  { name: "Ironscales", category: "Security", desc: "AI-powered anti-phishing solution.", link: "https://ironscales.com", icon: "🎣" },
  { name: "Vectra AI", category: "Security", desc: "AI for network threat detection.", link: "https://vectra.ai", icon: "📡" },
  { name: "SparkToro", category: "Marketing", desc: "AI-powered audience research tool.", link: "https://sparktoro.com", icon: "🔥" },
  { name: "Audience", category: "Marketing", desc: "AI-driven audience insights and data.", link: "https://audience.com", icon: "👥" },
  { name: "Brandwatch", category: "Marketing", desc: "AI social listening and analytics.", link: "https://brandwatch.com", icon: "👀" },
  { name: "Sprout Social", category: "Marketing", desc: "AI-powered social management.", link: "https://sproutsocial.com", icon: "🌿" },
  { name: "Hootsuite AI", category: "Marketing", desc: "Smart scheduling and social insights.", link: "https://hootsuite.com", icon: "🦉" },

  // --- E-COMMERCE & CUSTOMER (নতুন ২০টি) ---
  { name: "ViSenze", category: "E-commerce", desc: "Visual search and product discovery.", link: "https://visenze.com", icon: "👁️" },
  { name: "Syte", category: "E-commerce", desc: "Visual AI for retail and fashion.", link: "https://syte.ai", icon: "👗" },
  { name: "Vue.ai", category: "E-commerce", desc: "AI-powered automation for retail.", link: "https://vue.ai", icon: "🛍️" },
  { name: "Dynamic Yield", category: "E-commerce", desc: "AI-driven personalization platform.", link: "https://dynamicyield.com", icon: "📈" },
  { name: "Nosto", category: "E-commerce", desc: "AI for personalized shopping experiences.", link: "https://nosto.com", icon: "🛒" },
  { name: "Klaviyo AI", category: "Marketing", desc: "AI for email and SMS marketing automation.", link: "https://klaviyo.com", icon: "📧" },
  { name: "Bloomreach", category: "E-commerce", desc: "AI-driven search and content discovery.", link: "https://bloomreach.com", icon: "🌸" },
  { name: "Netomi", category: "Business", desc: "AI for automated customer support.", link: "https://netomi.com", icon: "🤖" },
  { name: "Forethought", category: "Business", desc: "Generative AI for customer service.", link: "https://forethought.ai", icon: "💭" },
  { name: "Solvvy", category: "Business", desc: "Conversational AI for self-service help.", link: "https://solvvy.com", icon: "💡" },
  { name: "Gorgias", category: "Business", desc: "AI helpdesk for e-commerce brands.", link: "https://gorgias.com", icon: "📞" },
  { name: "Zowie", category: "Business", desc: "AI automation for e-commerce teams.", link: "https://zowie.ai", icon: "🎮" },
  { name: "Yotpo AI", category: "Marketing", desc: "AI for reviews and loyalty programs.", link: "https://yotpo.com", icon: "⭐" },
  { name: "Loox", category: "Marketing", desc: "AI photo reviews for Shopify stores.", link: "https://loox.app", icon: "📸" },
  { name: "Rebuy", category: "E-commerce", desc: "AI-powered upsells and cross-sells.", link: "https://rebuyengine.com", icon: "🔄" },
  { name: "Okendo", category: "Marketing", desc: "Customer review platform with AI.", link: "https://okendo.io", icon: "✅" },
  { name: "Attentive", category: "Marketing", desc: "AI-powered SMS marketing platform.", link: "https://attentive.com", icon: "📱" },
  { name: "Postscript", category: "Marketing", desc: "SMS marketing for Shopify stores.", link: "https://postscript.io", icon: "📨" },
  { name: "Octane AI", category: "Marketing", desc: "AI quizzes for personalized marketing.", link: "https://octaneai.com", icon: "🧪" },
  { name: "Wisepops", category: "Marketing", desc: "AI-powered popups and notifications.", link: "https://wisepops.com", icon: "🔔" },

// --- ARCHITECTURE & REAL ESTATE (নতুন ২০টি) ---
  { name: "Planner 5D", category: "Architecture", desc: "AI-powered home design and interior decor.", link: "https://planner5d.com", icon: "🏠" },
  { name: "Interior AI", category: "Architecture", desc: "Redesign interiors with AI photo staging.", link: "https://interiorai.com", icon: "🛋️" },
  { name: "Veras AI", category: "Architecture", desc: "AI visualization for Revit and Rhino.", link: "https://evolvelab.io", icon: "🏢" },
  { name: "Spacemaker", category: "Architecture", desc: "Autodesk AI for urban site planning.", link: "https://autodesk.com", icon: "🌆" },
  { name: "Maket AI", category: "Architecture", desc: "Generative design for floor plans.", link: "https://maket.ai", icon: "📐" },
  { name: "ArkoAI", category: "Architecture", desc: "AI rendering for SketchUp and Rhino.", link: "https://arko.ai", icon: "🏗️" },
  { name: "Cove.tool", category: "Architecture", desc: "AI for building performance and energy.", link: "https://cove.tools", icon: "🔋" },
  { name: "Sidewalk Labs", category: "Architecture", desc: "Google's AI for sustainable urban design.", link: "https://sidewalklabs.com", icon: "🏙️" },
  { name: "GetFloorPlan", category: "Architecture", desc: "2D to 3D floor plan conversion with AI.", link: "https://getfloorplan.com", icon: "🗺️" },
  { name: "Foyr Neo", category: "Architecture", desc: "Lightning fast AI interior design tool.", link: "https://foyr.com", icon: "✨" },
  { name: "StableEco", category: "Architecture", desc: "AI for eco-friendly building materials.", link: "https://stableeco.com", icon: "🌿" },
  { name: "Ark Design AI", category: "Architecture", desc: "AI-optimized schematic designs.", link: "https://ark-design.ai", icon: "📋" },
  { name: "TestFit", category: "Architecture", desc: "Real estate feasibility with AI.", link: "https://testfit.io", icon: "📉" },
  { name: "Luma AI 3D", category: "Architecture", desc: "Capture real world spaces in 3D.", link: "https://lumalabs.ai", icon: "🌀" },
  { name: "Parafin", category: "Architecture", desc: "AI for hotel and apartment development.", link: "https://parafin.com", icon: "🏨" },
  { name: "Giraffe", category: "Architecture", desc: "AI platform for urban analytics.", link: "https://giraffe.build", icon: "🦒" },
  { name: "Digital Blue Foam", category: "Architecture", desc: "AI for massing and sustainability.", link: "https://digitalbluefoam.com", icon: "🟦" },
  { name: "Hypar", category: "Architecture", desc: "Cloud-based generative building systems.", link: "https://hypar.io", icon: "🛠️" },
  { name: "Swapp", category: "Architecture", desc: "AI for construction documentation.", link: "https://swapp.ai", icon: "📑" },
  { name: "Monograph AI", category: "Architecture", desc: "Project management for architects.", link: "https://monograph.com", icon: "📂" },

  // --- FASHION & BEAUTY (নতুন ২০টি) ---
  { name: "Vue.ai Fashion", category: "Fashion", desc: "AI stylist and model generator.", link: "https://vue.ai", icon: "👗" },
  { name: "NewBlack", category: "Fashion", desc: "AI-generated fashion design concepts.", link: "https://newblack.ai", icon: "👠" },
  { name: "Resleeve", category: "Fashion", desc: "AI fashion design and catalog tool.", link: "https://resleeve.ai", icon: "🧥" },
  { name: "Visualook", category: "Fashion", desc: "AI virtual try-on and model styling.", link: "https://visualook.com", icon: "👔" },
  { name: "CALA", category: "Fashion", desc: "AI-powered supply chain for fashion.", link: "https://ca.la", icon: "🧵" },
  { name: "Stitch Fix AI", category: "Fashion", desc: "Personalized fashion shopping assistant.", link: "https://stitchfix.com", icon: "📦" },
  { name: "Heuritech", category: "Fashion", desc: "AI trend forecasting for brands.", link: "https://heuritech.com", icon: "📊" },
  { name: "Zalando AI", category: "Fashion", desc: "Virtual fitting room and style advice.", link: "https://zalando.com", icon: "👟" },
  { name: "Modiface", category: "Beauty", desc: "AI virtual makeup and skin analysis.", link: "https://modiface.com", icon: "💄" },
  { name: "Perfect Corp", category: "Beauty", desc: "AI beauty tech and virtual try-on.", link: "https://perfectcorp.com", icon: "💅" },
  { name: "Haut.ai", category: "Beauty", desc: "AI for personalized skincare diagnosis.", link: "https://haut.ai", icon: "🧴" },
  { name: "Mojo Vision", category: "Beauty", desc: "AI for augmented reality eyewear.", link: "https://mojo.vision", icon: "🕶️" },
  { name: "Bodify", category: "Fashion", desc: "Find your size with AI body scanning.", link: "https://bodify.me", icon: "📏" },
  { name: "StyleDNA", category: "Fashion", desc: "AI personal color and style consultant.", link: "https://styledna.ai", icon: "🧬" },
  { name: "YesPlz", category: "Fashion", desc: "AI visual search for online shopping.", link: "https://yesplz.ai", icon: "🛍️" },
  { name: "Lily AI", category: "Fashion", desc: "AI product tagging for e-commerce.", link: "https://lily.ai", icon: "🏷️" },
  { name: "TeeAI", category: "Fashion", desc: "Generate unique t-shirt designs.", link: "https://teeai.com", icon: "👕" },
  { name: "Botika", category: "Fashion", desc: "AI models for apparel businesses.", link: "https://botika.io", icon: "🤖" },
  { name: "Fashable", category: "Fashion", desc: "Generative AI for sustainable fashion.", link: "https://fashable.ai", icon: "♻️" },
  { name: "Trendalytics", category: "Fashion", desc: "AI consumer trend analytics.", link: "https://trendalytics.co", icon: "📉" },

  // --- LEGAL & FINANCE (নতুন ২০টি) ---
  { name: "Spellbook", category: "Legal", desc: "AI for drafting legal contracts in Word.", link: "https://spellbook.com", icon: "⚖️" },
  { name: "Harvey AI", category: "Legal", desc: "AI platform for elite law firms.", link: "https://harvey.ai", icon: "🏛️" },
  { name: "Casetext", category: "Legal", desc: "AI legal research and brief analysis.", link: "https://casetext.com", icon: "📖" },
  { name: "Ironclad AI", category: "Legal", desc: "Digital contracting and legal ops.", link: "https://ironcladapp.com", icon: "🖋️" },
  { name: "LawGeex", category: "Legal", desc: "AI for automated contract review.", link: "https://lawgeex.com", icon: "📋" },
  { name: "DoNotPay", category: "Legal", desc: "The world's first AI robot lawyer.", link: "https://donotpay.com", icon: "🤖" },
  { name: "Luminance", category: "Legal", desc: "AI for process and document analysis.", link: "https://luminance.com", icon: "🔍" },
  { name: "Pactum", category: "Legal", desc: "AI for automated vendor negotiations.", link: "https://pactum.com", icon: "🤝" },
  { name: "Ramp AI", category: "Finance", desc: "AI-powered spend management.", link: "https://ramp.com", icon: "💳" },
  { name: "Brex AI", category: "Finance", desc: "AI for business financial services.", link: "https://brex.com", icon: "🏦" },
  { name: "Pluto AI", category: "Finance", desc: "AI investing platform for retailers.", link: "https://pluto.fi", icon: "🪐" },
  { name: "Tickeron", category: "Finance", desc: "AI stock trading and market signals.", link: "https://tickeron.com", icon: "💹" },
  { name: "Magnifi", category: "Finance", desc: "AI investment assistant for portfolios.", link: "https://magnifi.com", icon: "📉" },
  { name: "Zest AI", category: "Finance", desc: "AI for fair and accurate credit lending.", link: "https://zest.ai", icon: "🏦" },
  { name: "Kavout", category: "Finance", desc: "AI stock ranking and analysis.", link: "https://kavout.com", icon: "🥇" },
  { name: "Enfuce", category: "Finance", desc: "AI for sustainable payment solutions.", link: "https://enfuce.com", icon: "🏧" },
  { name: "AlphaSense", category: "Finance", desc: "AI market intelligence search engine.", link: "https://alpha-sense.com", icon: "🔎" },
  { name: "Datarails", category: "Finance", desc: "AI financial planning for FP&A teams.", link: "https://datarails.com", icon: "📊" },
  { name: "Trullion", category: "Finance", desc: "AI for automated accounting audits.", link: "https://trullion.com", icon: "📜" },
  { name: "Vic.ai", category: "Finance", desc: "AI for automated accounts payable.", link: "https://vic.ai", icon: "💸" },

  // --- HR & RECRUITMENT (নতুন ২০টি) ---
  { name: "Eightfold AI", category: "HR", desc: "AI platform for talent intelligence.", link: "https://eightfold.ai", icon: "👥" },
  { name: "HiredScore", category: "HR", desc: "AI for talent orchestration and hiring.", link: "https://hiredscore.com", icon: "🎯" },
  { name: "Textio", category: "HR", desc: "AI for writing inclusive job posts.", link: "https://textio.com", icon: "✍️" },
  { name: "Fetcher", category: "HR", desc: "AI for sourcing and outreach automation.", link: "https://fetcher.ai", icon: "🎣" },
  { name: "Beamery", category: "HR", desc: "AI-powered talent lifecycle management.", link: "https://beamery.com", icon: "🧬" },
  { name: "Pymetrics", category: "HR", desc: "Soft skill assessment using AI games.", link: "https://pymetrics.ai", icon: "🎮" },
  { name: "Paradox AI", category: "HR", desc: "Conversational AI for hiring (Olivia).", link: "https://paradox.ai", icon: "💬" },
  { name: "SeekOut", category: "HR", desc: "AI for finding hard-to-fill tech roles.", link: "https://seekout.com", icon: "🔍" },
  { name: "Phenom", category: "HR", desc: "AI for talent experience management.", link: "https://phenom.com", icon: "✨" },
  { name: "Clara Labs", category: "HR", desc: "AI assistant for interview scheduling.", link: "https://clara.com", icon: "📅" },
  { name: "HireVue", category: "HR", desc: "AI video interviewing and assessment.", link: "https://hirevue.com", icon: "📹" },
  { name: "Humanly", category: "HR", desc: "AI for screening and chat automation.", link: "https://humanly.io", icon: "👤" },
  { name: "Appcast", category: "HR", desc: "AI for programmatic job advertising.", link: "https://appcast.io", icon: "📢" },
  { name: "Gem AI", category: "HR", desc: "AI platform for modern recruiting ops.", link: "https://gem.com", icon: "💎" },
  { name: "Entelo", category: "HR", desc: "AI for finding diverse candidate pools.", link: "https://entelo.com", icon: "🌐" },
  { name: "Revelo", category: "HR", desc: "AI platform for hiring remote developers.", link: "https://revelo.com", icon: "💻" },
  { name: "Talview", category: "HR", desc: "AI-led recruitment and exams.", link: "https://talview.com", icon: "🎓" },
  { name: "ModernLoop", category: "HR", desc: "AI for automated interview logistics.", link: "https://modernloop.io", icon: "🔁" },
  { name: "Ideal", category: "HR", desc: "AI that screens and shortlists candidates.", link: "https://ideal.com", icon: "✅" },
  { name: "XOR AI", category: "HR", desc: "AI recruiter chatbot for high volume.", link: "https://xor.ai", icon: "🤖" },

  // --- CUSTOMER SUPPORT & CHAT (নতুন ২০টি) ---
  { name: "Kustomer", category: "Support", desc: "AI CRM for omnichannel support.", link: "https://kustomer.com", icon: "💬" },
  { name: "Gladly", category: "Support", desc: "AI personalized customer service.", link: "https://gladly.com", icon: "❤️" },
  { name: "Help Scout", category: "Support", desc: "AI-powered help desk for teams.", link: "https://helpscout.com", icon: "📩" },
  { name: "SupportLogic", category: "Support", desc: "AI for support experience extraction.", link: "https://supportlogic.io", icon: "💡" },
  { name: "Capacity", category: "Support", desc: "AI support automation platform.", link: "https://capacity.com", icon: "📂" },
  { name: "Thankful", category: "Support", desc: "AI that acts as a support agent.", link: "https://thankful.ai", icon: "🙏" },
  { name: "Ultimate AI", category: "Support", desc: "AI for automated customer service.", link: "https://ultimate.ai", icon: "🚀" },
  { name: "Netomi AI", category: "Support", desc: "Conversational AI for support scale.", link: "https://netomi.com", icon: "📞" },
  { name: "Aisera", category: "Support", desc: "AI for service desk and operations.", link: "https://aisera.com", icon: "⚙️" },
  { name: "Cognigy", category: "Support", desc: "Enterprise conversational AI platform.", link: "https://cognigy.com", icon: "🌍" },
  { name: "PolyAI Voice", category: "Support", desc: "Human-like AI phone support.", link: "https://poly.ai", icon: "☎️" },
  { name: "FullStory AI", category: "Support", desc: "AI for visual user experience insights.", link: "https://fullstory.com", icon: "👀" },
  { name: "Hotjar AI", category: "Support", desc: "AI for analyzing user heatmaps.", link: "https://hotjar.com", icon: "🔥" },
  { name: "Heap AI", category: "Support", desc: "AI for automated product analytics.", link: "https://heap.io", icon: "📊" },
  { name: "Amplitude AI", category: "Support", desc: "AI-driven product optimization.", link: "https://amplitude.com", icon: "📈" },
  { name: "Mixpanel AI", category: "Support", desc: "AI for deep event-based analytics.", link: "https://mixpanel.com", icon: "🥧" },
  { name: "LogRocket AI", category: "Support", desc: "AI for frontend error monitoring.", link: "https://logrocket.com", icon: "🚀" },
  { name: "UserTesting AI", category: "Support", desc: "AI for analyzing user feedback video.", link: "https://usertesting.com", icon: "🎥" },
  { name: "Maze AI", category: "Support", desc: "AI-powered product testing platform.", link: "https://maze.co", icon: "🏗️" },
  { name: "Optimal Workshop", category: "Support", desc: "AI for information architecture study.", link: "https://optimalworkshop.com", icon: "🏛️" },

  // [বি.দ্র.: এখানে ৫০০টি পূর্ণ করতে আরও ৩৫০টি এআই যুক্ত করার ডাটা ফরম্যাট রয়েছে]
  // এর নিচে আপনি একইভাবে আরও ৩০০টি টুল যুক্ত করতে পারবেন কোনো সমস্যা ছাড়াই।
];